# Generated by Django 3.2.4 on 2021-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=0, max_length=40, verbose_name='姓名'),
        ),
    ]
